### ISSUE TITLE
no attribute for tags.STUDENT

### ISSUE THREAD

**Issue by lrochette** [CloudSurgeon/landshark-toolchain-blueprints#1]
it looks like  the same issue than https://github.com/terraform-providers/terraform-provider-aws/issues/2716

Error: Error running plan: 5 error(s) occurred:

* output.GUACAMOLE: Resource 'aws_instance.de' does not have attribute 'tags.STUDENT' for variable 'aws_instance.de.*.tags.STUDENT'
* output.DE: Resource 'aws_instance.de' does not have attribute 'tags.STUDENT' for variable 'aws_instance.de.*.tags.STUDENT'
* output.LT: Resource 'aws_instance.de' does not have attribute 'tags.STUDENT' for variable 'aws_instance.de.*.tags.STUDENT'
* output.TOOLING: Resource 'aws_instance.de' does not have attribute 'tags.STUDENT' for variable 'aws_instance.de.*.tags.STUDENT'
* output.LS: Resource 'aws_instance.de' does not have attribute 'tags.STUDENT' for variable 'aws_instance.de.*.tags.STUDENT'

I'm running terraform version 0.11.3

**Comment by lrochette** [comment]
Reverting back to 0.10.8 seems to solve the issue

**Comment by CloudSurgeon** [comment]
Closing issue. Per README, use version 10.8.
